### PR TITLE
Milestone 2: User Interface placeholder and mocked logic

### PR DESCRIPTION
**Pull request by SlowKingV**
> The final point of this milestone is to make sure that you thought about all actions needed to play Tic Tac Toe. It does not need to work yet - this will be done in the next milestone.

This milestone has been finished and you can add your movements up to three times before the game finishes.

### CODE REVIEW

**Review by fatymahmed — CHANGES_REQUESTED** [review]
## Hi @SlowKingV @srueda27,
You have most of the steps for the game flow 👏👏, just a few are missing, let's add those that are missing.
- [ ]  Make sure your main.rb uses puts/print and `get.chomp` commands. [see screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/main_rb.png) from Pathwright. 

**Behaviour**
Use the following game flow to make sure that you haven't missed any step [screenshot of hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from Pathwright)

   - [x] [OPTIONAL] game ask players for their names
   - [x] [REQUIRED] game tells which player turn it is
   - [x] [REQUIRED] game asks player to select from available moves
   - [x] [REQUIRED] game informs player if selected move is invalid
   - [x] [REQUIRED] game displays board after player move
   - [x] [REQUIRED] game informs player if selected move is a winning move
   - [x] [REQUIRED] game informs player if selected move is a draw move
   - [x] [REQUIRED] game repeats all actions for next player's move

**Implementation details**
- [x] A loop is needed in this game (you could use a `while` loop or anything similar) [OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png). 
- [x] The loop should be terminated at some point (after a winning move or draw to be more specific). It can be done with a variable.

### Status: Changes Required
_Feel free to reach out to me on slack(Fatima), If you have any questions, I'd be happy to help._

**Comment by SlowKingV** [comment]
**@fatymahmed I did almost all the changes except for the one about** `get.chomp`.
I know pathwright recommends using it, however `get.strip` will get rid of any white space after AND before the user input. That said I think this is better for this situation since this will take care of any undesired space.

**Comment by fatymahmed** [comment]
I agree, it's a good alternative,  You don't need to change it to get.chomp, what you have is good enough

**Comment by shshamim63** [comment]
## Status: :tada: Approved :tada: 
___
Hi @SlowKingV  and @srueda27 :wave: ,
Awesome job :clap: . You have covered all the issues raised by the previous reviewer. Great job. Nothing is blocking me to approve this project. So, this :+1: is from me, you can go ahead.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

**Pull request merged**
